services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - matchaNetwork
    env_file:
      - ./.env
    ports:
      - "3005:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    env_file:
      - ./.env
    environment:
      PMA_HOST: mysql
    networks:
      - matchaNetwork

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    restart: always
    volumes:
      - api:/app
    ports:
      - 3000:3000
    networks:
      - matchaNetwork
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env

  websocket:
    build:
      context: ./websocket/
    container_name: websocket
    restart: always
    volumes:
      - websocket:/app
    ports:
      - 3001:3001
    expose:
      - '3001'
    networks:
      - matchaNetwork
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    restart: always
    volumes:
      - frontend:/app
    expose:
      - '1212'
    ports:
      - 1212:1212
    networks:
      - matchaNetwork
    depends_on:
      - mysql

volumes:
  frontend:
    driver: local
    name: frontend
    driver_opts:
      o: bind
      type: none
      device: ./frontend
  websocket:
    driver: local
    name: websocket
    driver_opts:
      o: bind
      type: none
      device: ./websocket
  api:
    driver: local
    name: api
    driver_opts:
      o: bind
      type: none
      device: ./api
  db:
    name: db

networks:
  matchaNetwork:
    driver: bridge
    name: matchaNetwork