services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - api
    volumes:
      - api:/app
    ports:
      - "1212:1212"
      - "3000:3000"
    networks:
      - matchaNetwork
    command: /bin/sh -c "
      mkdir /usr/share/nginx/html/backend &&
      cp -R /app/* /usr/share/nginx/html/backend &&
      chown -R nginx:nginx /usr/share/nginx/html/backend &&
      chmod -R 755 /usr/share/nginx/html/backend &&
      nginx -g 'daemon off;'"

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    container_name: api
    restart: always
    volumes:
      - api:/app
#    ports:
#      - 3000:3000
    expose:
      - 9000
    networks:
      - matchaNetwork
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env