services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    expose:
      - '5432'
    networks:
      - matchaNetwork
    env_file:
      - ./.env

  api:
    build:
      context: ./api/
    container_name: api
    restart: always
    volumes:
      - api:/api
    expose:
      - '3000'
    networks:
      - matchaNetwork
    depends_on:
      - mysql

  websocket:
    build:
      context: ./websocket/
    container_name: websocket
    restart: always
    volumes:
      - websocket:/app
    expose:
      - '3001'
    networks:
      - matchaNetwork
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    restart: always
    volumes:
      - frontend:/app
    expose:
      - '1212'
    ports:
      - 1212:1212
    networks:
      - matchaNetwork
    depends_on:
      - mysql

volumes:
  frontend:
    driver: local
    name: frontend
    driver_opts:
      o: bind
      type: none
      device: ./frontend
  websocket:
    driver: local
    name: websocket
    driver_opts:
      o: bind
      type: none
      device: ./websocket
  api:
    driver: local
    name: api
    driver_opts:
      o: bind
      type: none
      device: ./api
  db:
    name: db

networks:
  matchaNetwork:
    driver: bridge
    name: matchaNetwork