services:
  mysql:
    image: mysql:latest
    container_name: postgres
    restart: always
    volumes:
      - db:/var/lib/mysql/data
    expose:
      - '5432'
    networks:
      - matchaNetwork
    env_file:
      - ./.env

  api:
    build:
      context: ./api/
    container_name: api
    image: api
    restart: always
    volumes:
      - api:/app
    ports:
      - 3000:3000
    networks:
      - matchaNetwork
    depends_on:
      - mysql
    env_file:
      - ./api/.env

  websocket:
    build:
      context: ./websocket/
    container_name: websocket
    image: websocket
    restart: always
    volumes:
      - api:/app
    ports:
      - 3001:3001
    networks:
      - matchaNetwork
    depends_on:
      - mysql
    env_file:
      - ./websocket/.env

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    image: frontend
    restart: always
    volumes:
      - api:/app
    ports:
      - 3002:3002
    networks:
      - matchaNetwork
    depends_on:
      - mysql
    env_file:
      - ./frontend/.env

volumes:
  api:
    name: api
  db:
    name: db

networks:
  matchaNetwork:
    driver: bridge
    name: matchaNetwork