openapi: 3.0.3
info:
  title: Swagger Matcha - OpenAPI 3.0
  version: 0.0.1
servers:
  - url: http://localhost:3000/api/
tags:
  - name: auth
    description: Auth routes
  - name: profile
    description: Profile routes
paths:
  /auth/login:
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/User"
                  - type: object
                    properties:
                      email:
                        type: string
                        format: email
        "404":
          description: User not found
  /auth/register:
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        "200":
          description: OK
  /auth/logout:
    delete:
      tags:
        - auth
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /auth/forgot-password:
    post:
      tags:
        - auth
      responses:
        "200":
          description: OK
  /auth/reset-password:
    post:
      tags:
        - auth
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /auth/verify-email:
    post:
      tags:
        - auth
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /profile/@me:
    patch:
      tags:
        - profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
    delete:
      tags:
        - profile
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /profile/@me/notifications:
    get:
      tags:
        - profile
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
    post:
      tags:
        - profile
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /profile/@me/channels:
    get:
      tags:
        - profile
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
    post:
      tags:
        - profile
      requestBody:
        content:
            application/json:
              schema:
                type: object
                properties:
                  recipient_id:
                    type: integer
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /profile/@me/channels/{channel.id}/messages:
    get:
      tags:
        - profile
      parameters:
        - name: channel.id
          in: path
          description: Channel
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "401":
          description: Unauthorized
    post:
      tags:
        - profile
      parameters:
        - name: channel.id
          in: path
          description: Channel
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /profile/{user.username}:
    get:
      tags:
        - profile
      parameters:
        - name: user.username
          in: path
          description: Username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized
  /profile/{user.username}/like:
    post:
      tags:
        - profile
      parameters:
        - name: user.username
          in: path
          description: Username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
    delete:
      tags:
        - profile
      parameters:
        - name: username
          in: path
          description: Username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          readOnly: true
        first_name:
          type: string
          example: "John"
        last_name:
          type: string
          example: "Doe"
        age:
          type: integer
          minimum: 18
        gender:
          type: string
          enum: ["M", "F", "O"]
        sexual_preferences:
          type: string
          enum: ["A", "M", "F", "O"]
        biography:
          type: string
        tags:
          type: array
          items:
            type: string
            pattern: '^#[a-zA-Z]{1,25}$'
          example: ["#cheese", "#geek"]
        pictures:
          type: array
          items:
            type: string
            format: byte
          minItems: 1
          maxItems: 5
        localisation:
          type: string
          nullable: true
        premium:
          type: boolean
          readOnly: true
        profile_verified:
          type: boolean
          readOnly: true
        fame_rating:
          type: number
          format: float
          default: 100
          readOnly: true
    Message:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        content:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT