name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          working-directory: ./api


      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5.26
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett