name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: |
          cd api
          composer install

      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1
        with:
          filenames: example.env

      - name: Check environment variable SECRET_KEY
        run: echo $SECRET_KEY

      - name: PHPUnit Tests
        run: |
          cd api
          ./vendor/bin/phpunit --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
